# Generated by Django 5.1.3 on 2024-11-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jenis_umkm', models.CharField(max_length=150)),
                ('nama_umkm', models.CharField(max_length=150)),
                ('alamat_umkm', models.TextField()),
                ('foto_umkm', models.ImageField(upload_to='')),
                ('deskripsi', models.TextField()),
                ('dana', models.CharField(max_length=150)),
                ('bagi_hasil', models.CharField(default='12% Per tahun', max_length=50)),
                ('tenor', models.CharField(default='Per bulan', max_length=50)),
                ('proposal', models.FileField(upload_to='proposals/')),
                ('laporan_keuangan', models.FileField(upload_to='laporan_keuangan/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('ktp', models.ImageField(upload_to='ktp_images/')),
                ('npwp', models.CharField(max_length=20)),
                ('no_rek', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
