# Generated by Django 5.1.3 on 2024-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0002_profile_investor_foto_alter_umkm_foto_umkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('waktu', models.DateTimeField()),
                ('pembicara', models.CharField(max_length=200)),
                ('link_zoom', models.URLField()),
                ('meeting_id', models.CharField(max_length=100)),
                ('kata_sandi', models.CharField(max_length=50)),
                ('gambar', models.JSONField(default=list)),
            ],
        ),
    ]
