# Generated by Django 5.1.3 on 2024-12-01 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0003_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='kata_sandi',
            new_name='passcode',
        ),
        migrations.AddField(
            model_name='webinar',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='gambar',
            field=models.ImageField(upload_to='webinar_images/'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='meeting_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='waktu',
            field=models.TimeField(),
        ),
    ]
