# Generated by Django 5.1.3 on 2024-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0006_pendanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendanaan',
            name='tanggal_pendanaan',
            field=models.DateTimeField(),
        ),
    ]
