# Generated by Django 5.1.3 on 2024-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0007_alter_pendanaan_tanggal_pendanaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_investor',
            name='perjanjian_pendanaan',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dokumen/'),
        ),
        migrations.AddField(
            model_name='profile_investor',
            name='surat_kuasa',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dokumen/'),
        ),
    ]
