# Generated by Django 5.1.3 on 2024-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0008_profile_investor_perjanjian_pendanaan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_investor',
            name='perjanjian_pendanaan',
        ),
        migrations.RemoveField(
            model_name='profile_investor',
            name='surat_kuasa',
        ),
        migrations.AddField(
            model_name='pendanaan',
            name='denda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pendanaan',
            name='status_pendanaan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
