# Generated by Django 5.1.3 on 2024-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0011_profile_investor_total_aset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_investor',
            name='total_aset',
            field=models.IntegerField(),
        ),
    ]
