# Generated by Django 5.1.3 on 2024-12-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0012_alter_profile_investor_total_aset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_investor',
            name='total_aset',
        ),
    ]
