# Generated by Django 5.1.3 on 2024-12-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0014_alter_pendanaan_tanggal_pendanaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Linkbiz.profile_investor'),
        ),
    ]
