# Generated by Django 5.1.3 on 2024-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0016_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendanaan',
            name='status_pendanaan',
            field=models.CharField(blank=True, choices=[('Lancar', 'Lancar'), ('Terlambat 30-60 Hari', 'Terlambat 30-60 Hari'), ('Terlambat 61-90 Hari', 'Terlambat 61-90 Hari'), ('Kurang Lancar > 90 Hari', 'Kurang Lancar > 90 Hari'), ('Ditutup', 'Ditutup')], max_length=50, null=True),
        ),
    ]
