# Generated by Django 5.1.3 on 2024-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0018_withdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='jumlah_tarik',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
