# Generated by Django 5.1.3 on 2024-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0019_alter_withdrawrequest_jumlah_tarik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='jumlah_tarik',
            field=models.IntegerField(),
        ),
    ]
