# Generated by Django 5.1.3 on 2024-12-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0020_alter_withdrawrequest_jumlah_tarik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='dana',
            field=models.IntegerField(),
        ),
    ]
