# Generated by Django 5.1.3 on 2024-12-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0021_alter_umkm_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkm',
            name='dana',
            field=models.CharField(max_length=150),
        ),
    ]
