# Generated by Django 5.1.3 on 2024-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkbiz', '0022_alter_umkm_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendanaan',
            name='status_pendanaan',
            field=models.CharField(blank=True, choices=[('Lancar', 'Lancar'), ('Terlambat 30-60 Hari', 'Terlambat 30-60 Hari'), ('Terlambat 61-90 Hari', 'Terlambat 61-90 Hari'), ('Kurang Lancar > 90 Hari', 'Kurang Lancar > 90 Hari')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendanaan',
            name='tanggal_pendanaan',
            field=models.DateTimeField(),
        ),
    ]
